[package]
name = "encode-vpx-webm"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
yuvutils-rs = "0.8.1"
webm = { version = "2.0.0" }
vpx-encode = { version = "0.6.2", features = ["vp9"] }


